import mobile from "../EcommeraceModule/StoreAssets/img/mobile2.jpg";
import laptop from "../EcommeraceModule/StoreAssets/img/laptop2.jpg";
// import watch from "../EcommeraceModule/StoreAssets/img/watch2.jpg";
// import speaker from "../EcommeraceModule/StoreAssets/img/Speaker2.jpg";
import SP1 from "../EcommeraceModule/StoreAssets/img/SpecialProduct1/SP1.jpg";
import SP2 from "../EcommeraceModule/StoreAssets/img/SpecialProduct1/SP2.jpg";
import SP3 from "../EcommeraceModule/StoreAssets/img/SpecialProduct1/SP3.jpg";
// import SP4 from "../../EcommeraceModule/StoreAssets/img/SpecialProduct1.jpg";
import sp1 from "../EcommeraceModule/StoreAssets/img/SpecialProduct2/sp1.jpg";
import sp2 from "../EcommeraceModule/StoreAssets/img/SpecialProduct2/sp2.jpg";
import sp3 from "../EcommeraceModule/StoreAssets/img/SpecialProduct2/sp3.jpg";

import camera from "../EcommeraceModule/StoreAssets/img/camers.jpg";
import headphone from "../EcommeraceModule/StoreAssets/img/headphone1.jpg";
import speaker from "../EcommeraceModule/StoreAssets/img/speaker.jpg";
import tab from "../EcommeraceModule/StoreAssets/images/tab.jpg";
import watch from "../EcommeraceModule/StoreAssets/images/watch.jpg";
import cameraHovered from "../EcommeraceModule/StoreAssets/img/CameraHovered.jpg";
import headphonehover from "../EcommeraceModule/StoreAssets/img/headphonehover.jpg";
import speakerhover from "../EcommeraceModule/StoreAssets/img/speakerhover.jpg";
import tabhover from "../EcommeraceModule/StoreAssets/images/tab1.jpg";
import watchhover from "../EcommeraceModule/StoreAssets/img/watchhovered.jpg";

export const products = [
  {
    id: 1,
    category: 0,
    price: "100.00",
    heading: "Olympus pen, EZ lens",
    brand: "Havells",
    productCardImage: camera,
    imageonHover: cameraHovered,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 4, review: "Very Nice" },
      { stars: 4, review: "Very Beautiful Products" },
      { stars: 4, review: "Recomended" },
    ],
  },
  {
    id: 2,
    productCardImage: headphone,
    heading: "Headphones for Kids",
    brand: "Havells",
    price: "500",
    imageonHover: headphonehover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 4, review: "Very Good Products" },
      { stars: 4, review: "Very Nice" },
      { stars: 4, review: "Very Beautiful Products" },
      { stars: 4, review: "Recomended" },
    ],
  },
  {
    id: 3,
    productCardImage: speaker,
    heading: "Portable Speakers",
    brand: "Bajaj",
    price: "200",
    imageonHover: speakerhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 3, review: "Very Good Products" },
      { stars: 3, review: "Very Nice" },
      { stars: 3, review: "Very Beautiful Products" },
      { stars: 3, review: "Recomended" },
    ],
  },
  {
    id: 4,
    productCardImage: tab,
    heading: "Tab from Havells",
    brand: "Havells",
    price: "200",
    imageonHover: tabhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Recomended" },
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Beautiful Products" },
    ],
  },
  {
    id: 5,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 4, review: "Very Good Products" },
      { stars: 4, review: "Very Nice" },
      { stars: 4, review: "Very Beautiful Products" },
      { stars: 4, review: "Recomended" },
    ],
  },
  {
    id: 6,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 7,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 8,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 9,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 10,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 11,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 12,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 13,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 14,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 15,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 16,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 17,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 18,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 19,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 20,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 21,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 22,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 23,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 24,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 25,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 26,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 27,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 28,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 29,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 30,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
  {
    id: 31,
    productCardImage: watch,
    heading: "Watch from Sony",
    brand: "Sony",
    price: "200",
    imageonHover: watchhover,
    category: 0,
    images: [SP1, SP2, SP3],
    productColors: [
      "rgb(181, 206, 222)",
      "rgb(186, 183, 186)",
      "rgb(243, 203, 196)",
    ],
    tags: ["laptop", "oppo", "speaker", "tablet"],
    name: "Honor T1 7.0 1 GB RAM 8 GB ROM 7 inch with Wi-Fi+3G Tablet",
    description:
      "Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.",
    feedback: [
      { stars: 5, review: "Very Good Products" },
      { stars: 5, review: "Very Nice" },
      { stars: 5, review: "Very Beautiful Products" },
      { stars: 5, review: "Recomended" },
    ],
  },
];
